### ISSUE TITLE
Unable to Locate Downloadable Code

### ISSUE THREAD

**Issue by katyukuki** [HumanAIGC/AnimateAnyone#1]
Hello,

I am eagerly looking forward to your amazing tool's demo. I attempted to download the code and understood the general explanation, but I could not locate the actual source files. If the source has already been published, I would be grateful if you could direct me to it. I am looking forward to future updates.

Thank you.

**Comment by migero** [comment]
thats cus there is none

**Comment by katyukuki** [comment]
Thank you.
