### ISSUE TITLE
When will the source code be released?

### ISSUE THREAD

**Issue by Akki-0** [HumanAIGC/AnimateAnyone#2]
Hello! I am very interested in your impressive and amazing work after watching your demo!
I wonder when will you release your source code because it seems amazing!

Thank you!

**Comment by HildaM** [comment]
I waited anxiously.

**Comment by migero** [comment]
released if ever

**Comment by yinfan98** [comment]
anxiously too！

**Comment by Tybost** [comment]
This is big! waiting

**Comment by CustodialMatter** [comment]
when source <3

**Comment by smyja** [comment]
Where's the code? :)

**Comment by cchance27** [comment]
Has the researchers said anything about the release? Or if they even will? It's not a perfect model but definitely better than the rest thats available

**Comment by mike4b** [comment]
+1

**Comment by vignesh-fynd** [comment]
Waiting eagarly.

**Comment by hradec** [comment]
+1
If not the source code, at least the trained model with code on how to use it. 

In an ideal world, the source code and the training dataset to create the trained model would be perfect, so people can re-train and improve on it. 

But at least the trained model and a "how to use" source code is already enough...

**Comment by HumanAIGC** [comment]
please refer to our official updates  #12
