### ISSUE TITLE
人未至，吠声先到？

### ISSUE THREAD

**Issue by jzyzxx** [HumanAIGC/AnimateAnyone#52]
源码还没发布，就斩获11k星，别辜负大家的期待？

**Comment by jinqinn** [comment]
阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。
当然不能完全否定会放鸽子。

**Comment by ReEnMikki** [comment]
The hype is big because this is very well going to revolutionize indie animators. Maybe now everyone can create their own animes) or something else

**Comment by LianShuaiLong** [comment]
> 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。

阿里另外一个开源项目dreaMoving比animate-anyone论文发布的晚好久，现在人家都已经开源出来了试用demo，https://www.modelscope.cn/studios/vigen/video_generation/summary，animate-anyone这都2个月了，一个试用模型都没有么？

**Comment by jzyzxx** [comment]
> 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。

我承认我说话大声了点，加油

**Comment by LianShuaiLong** [comment]
> 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。

这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023
dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary
从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有

**Comment by fwbx529** [comment]
> > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> 
> 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有

今天听说有demo了，通义千问app输入全民舞王可以试用

**Comment by LianShuaiLong** [comment]
> > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > 
> > 
> > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> 
> 今天听说有demo了，通义千问app输入全民舞王可以试用

试用了一下，感觉通义千问app里面的全民舞王用的应该是dreaMoving

**Comment by silverbulletmdc** [comment]
> > > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > > 
> > > 
> > > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> > 
> > 
> > 今天听说有demo了，通义千问app输入全民舞王可以试用
> 
> 试用了一下，感觉通义千问app里面的全民舞王用的应该是dreaMoving

完全不是一个东西啊。。dreaMoving是换脸+驱动，而不是在原图背景下驱动，相对简单些

**Comment by LianShuaiLong** [comment]
> > > > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > > > 
> > > > 
> > > > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> > > 
> > > 
> > > 今天听说有demo了，通义千问app输入全民舞王可以试用
> > 
> > 
> > 试用了一下，感觉通义千问app里面的全民舞王用的应该是dreaMoving
> 
> 完全不是一个东西啊。。dreaMoving是换脸+驱动，而不是在原图背景下驱动，相对简单些

错了哈，dreaMoving可不是简单的换脸，dreaMoving的除了脸以外其他部分区域也是生成的，可以试用一下；

**Comment by LianShuaiLong** [comment]
> > > > > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > > > > 
> > > > > 
> > > > > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> > > > 
> > > > 
> > > > 今天听说有demo了，通义千问app输入全民舞王可以试用
> > > 
> > > 
> > > 试用了一下，感觉通义千问app里面的全民舞王用的应该是dreaMoving
> > 
> > 
> > 完全不是一个东西啊。。dreaMoving是换脸+驱动，而不是在原图背景下驱动，相对简单些
> 
> 错了哈，dreaMoving可不是简单的换脸，dreaMoving的除了脸以外其他部分区域也是生成的，可以试用一下；
关于"原图背景下驱动"这一点，我再去看看anymate-anyone的论文

**Comment by LianShuaiLong** [comment]
> > > > > > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > > > > > 
> > > > > > 
> > > > > > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> > > > > 
> > > > > 
> > > > > 今天听说有demo了，通义千问app输入全民舞王可以试用
> > > > 
> > > > 
> > > > 试用了一下，感觉通义千问app里面的全民舞王用的应该是dreaMoving
> > > 
> > > 
> > > 完全不是一个东西啊。。dreaMoving是换脸+驱动，而不是在原图背景下驱动，相对简单些
> > 
> > 
> > 错了哈，dreaMoving可不是简单的换脸，dreaMoving的除了脸以外其他部分区域也是生成的，可以试用一下；
> > 关于"原图背景下驱动"这一点，我再去看看anymate-anyone的论文

论文的确没有明确说“原图背景下驱动”，但是根据论文中的Fig,确实能说明“原图背景下驱动”，感谢提醒；期待anymate-anyone开源吧，很有意义的工作

**Comment by LianShuaiLong** [comment]
> > > 阿里的开源项目，代码一般会延迟两个月的时间发布，内部走流程啥的。 当然不能完全否定会放鸽子。
> > 
> > 
> > 这个阿里另外一个团队开源项目dreaMoving的首次code提交日期：Commits on Dec 7, 2023 dreaMoving在12月31号已经开放了demo试用链接：https://www.modelscope.cn/studios/vigen/video_generation/summary 从首次提交到开放demo用了不到一个月时间，反观animate-anyone两个月了，除了star数，啥进展都没有
> 
> 今天听说有demo了，通义千问app输入全民舞王可以试用

效果炸裂，牛逼
