### ISSUE TITLE
project is from the Alibaba development team?

### ISSUE THREAD

**Issue by shiyueGG** [HumanAIGC/AnimateAnyone#9]
When you hear that a project is from the Alibaba development team, you should understand the following points:
1. The possibility of it being open-source is low.
2. There's more talk than action.
3. Many projects are abandoned halfway.

**Comment by durenzidu** [comment]
怎么还有人专门黑的

**Comment by shiyueGG** [comment]
> 怎么还有人专门黑的

这是事实，和专门不专门没什么关系。

**Comment by yhyu13** [comment]
lul
