### ISSUE TITLE
Some reproducible results

### ISSUE THREAD

**Issue by shaoguowen** [HumanAIGC/AnimateAnyone#94]
https://github.com/HumanAIGC/AnimateAnyone/assets/57278682/bd42d109-90d1-4d4c-a3ac-2996b6521418

**Comment by Collin-Budrick** [comment]
What code did you use to make this?

**Comment by shaoguowen** [comment]
> What code did you use to make this?

pls follow this: https://github.com/TMElyralab/MusePose/issues/19

**Comment by ApolloRay** [comment]
> > What code did you use to make this?
> 
> pls follow this: [TMElyralab/MusePose#19](https://github.com/TMElyralab/MusePose/issues/19)

这也不叫复现啊，方法都不一样。

**Comment by shaoguowen** [comment]
> > > What code did you use to make this?
> > 
> > 
> > pls follow this: [TMElyralab/MusePose#19](https://github.com/TMElyralab/MusePose/issues/19)
> 
> 这也不叫复现啊，方法都不一样。

一样的啊，MusePose是在AnimateAnyone的复现版本 [Moore-AnimateAnyone](https://github.com/MooreThreads/Moore-AnimateAnyone) 上做的改进。你要说跟AnimateAnyone一模一样不一定，毕竟他都没开源

**Comment by yuchenli-sony** [comment]
the face looks not good

**Comment by shaoguowen** [comment]
https://github.com/HumanAIGC/AnimateAnyone/assets/57278682/b8e7a522-33ad-4cf9-a50f-9a951f86fbad

upper body test

**Comment by yuchenli-sony** [comment]
so weired
